language: groovy
sudo: false
jdk:
- oraclejdk8

addons:
  firefox: "46.0.1"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
- ./gradlew clean guiTest build --stacktrace -Dstubrunner.skip-local-repo=true --info

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

env:
- TERM=dumb

after_success:
- ./gradlew test jacocoTestReport coveralls -Pcoverage

